#!/bin/bash

while true; do
    clear
    echo "Elichika Menu:"
    echo "1. Run Server (Old)"
    echo "2. Run Server (New)"
    echo "3. Build DB (Old) (GL) (Android) (English)"
    echo "4. Build DB (Old) (GL) (Android) (ALL Language)"
    echo "5. Build DB (Old) (JP) (Android)"
    echo "6. Build DB (Old) (ALL)"
	echo "7. Make New User (Old) (GL)"
	echo "8. Make New User (Old) (JP)"
	echo "9. Add New Costume (Old) (GL) (English)"
	echo "10. Clone Costume to Another Member (Old) (GL)"
	echo "11. Install Dependencies"
	echo "12. Update Script"
	echo "13. Update Menu (Restart to Apply Changes)"
	echo "14. Switch to LocalHost (Old)"
	echo "15. Switch to Catfolk (Old)"
    echo "0. Exit"

    read -p "Enter your choice: " choice

    case $choice in
        1)
			clear
            pkill elichika
			cd ~/elichika-RusdiNgawi
			./elichika
			cd ~/
            ;;
        2)
			clear
            pkill elichika
			cd ~/elichika
			./elichika
			cd ~/
            ;;
        3)
			clear
			pkill elichika
			cd ~/elichika-RusdiNgawi
			python bin/encryptdbset.py static update assets/db/gl/masterdata_a_en
			cd ~/
            ;;
        4)
			clear
			pkill elichika
			cd ~/elichika-RusdiNgawi
			python bin/encryptdbset.py static update assets/db/gl/masterdata_a_en assets/db/gl/masterdata_a_ko assets/db/gl/masterdata_a_zh
			cd ~/
            ;;
        5)
			clear
			pkill elichika
			cd ~/elichika-RusdiNgawi
			python bin/encryptdbset.py static update assets/db/jp/masterdata_a_ja
			cd ~/
            ;;
        6)
			clear
			pkill elichika
			cd ~/elichika-RusdiNgawi
			python bin/encryptdbset.py static update assets/db/gl/masterdata_a_en assets/db/gl/masterdata_a_ko assets/db/gl/masterdata_a_zh assets/db/gl/masterdata_i_en assets/db/gl/masterdata_i_ko assets/db/gl/masterdata_i_zh
			python bin/encryptdbset.py static update assets/db/jp/masterdata_a_ja assets/db/jp/masterdata_i_ja
			cd ~/
            ;;
        7)
			clear
			cd ~/elichika-RusdiNgawi
			cp serverdata_gl.db assets/db/serverdata.db
			./elichika
			cd ~/
            ;;
        8)
			clear
			cd ~/elichika-RusdiNgawi
			./elichika make jp new
			cd ~/
            ;;
        9)
			clear
			cd ~/elichika-RusdiNgawi
			python costume_addon_termux.py
			cd ~/
            ;;
        10)
			clear
			cd ~/elichika-RusdiNgawi
			python costume_clone.py
			cd ~/
            ;;
        11)
			clear
			cd ~/
			pkg update
			pkg upgrade
			pkg install python
			pkg install git
			git clone https://github.com/NaufalFajri/astool.git astool-dist
			pip install ./astool-dist/hwdecrypt_src
			cd ~/
            ;;
        12)
			clear
			pkill elichika
			cd ~/
			cd ~/elichika-RusdiNgawi
			curl -L https://github.com/NaufalFajri/as-utility/raw/main/config_localhost.json -o config_localhost.json
			curl -L https://codeberg.org/arina999999997/nozomi/raw/branch/master/catfolk_cdn.json -0 config_catfolk.json
			curl -L https://raw.githubusercontent.com/NaufalFajri/as-utility/main/costume_addon_termux.py -o costume_addon_termux.py
			curl -L https://raw.githubusercontent.com/NaufalFajri/as-utility/main/costume_clone.py -o costume_clone.py
			cd ~/
            ;;
        13)
			clear
			pkill elichika
			cd ~/
			curl -L https://raw.githubusercontent.com/NaufalFajri/as-utility/main/run -o run
			echo "Restart to Apply Changes"
        14)
			clear
			pkill elichika
			cd ~/elichika-RusdiNgawi
			cp config_localhost.json config.json
        15)
			clear
			pkill elichika
			cd ~/elichika-RusdiNgawi
			cp config_catfolk.json config.json
            exit 0
            ;;
        0)
			clear
            echo "Exiting..."
            exit 0
            ;;
        *)
            echo "Invalid choice. Please enter a valid option."
            ;;
    esac

    read -p "Press Enter to continue..."
done
