#!/bin/bash

while true; do
    clear
    echo "https://github.com/NaufalFajri/as-utility/"
    echo "Elichika Arina Menu (Global Client):"
    echo "1. Run Server"
	echo "2. Add New Costume"
	echo "3. Add New Live"
	echo "4. Import SQL"
	echo "5. Install / Update Dependencies & Script"
	echo "6. Switch to LocalHost"
	echo "7. Switch to Catfolk"
    echo "0. Exit"

    read -p "Enter your choice: " choice

    case $choice in
        1)
			clear
            pkill elichika
			cd ~/elichika
			./elichika
			cd ~/
            ;;
        2)
			clear
      pkill elichika
			cd ~/elichika
			echo "PLEASE CHANGE DOWNLOAD SETTINGS TO FULL"
			echo "ONCE THE DOWNLOAD IS COMPLETED, YOU CAN ADD PROCEED THIS"
			echo "THIS WILL PREVENT ADDITIONAL FILES FROM BEING DELETED DURING DOWNLOAD CONFIRMATION"
			read -p "Press Enter to proceed" _dummy3
			python costume_addon_installer.py
			cd ~/
            ;;
        3)
			clear
      pkill elichika
			cd ~/elichika
			echo "PLEASE CHANGE DOWNLOAD SETTINGS TO FULL"
			echo "ONCE THE DOWNLOAD IS COMPLETED, YOU CAN ADD PROCEED THIS"
			echo "THIS WILL PREVENT ADDITIONAL FILES FROM BEING DELETED DURING DOWNLOAD CONFIRMATION"
			read -p "Press Enter to proceed" _dummy334
			python live_addon_installer.py
			cd ~/
            ;;
        4)
			clear
      pkill elichika
			cd ~/elichika
			echo "PLEASE CHANGE DOWNLOAD SETTINGS TO FULL"
			echo "ONCE THE DOWNLOAD IS COMPLETED, YOU CAN ADD PROCEED THIS"
			echo "THIS WILL PREVENT ADDITIONAL FILES FROM BEING DELETED DURING DOWNLOAD CONFIRMATION"
			read -p "Press Enter to proceed" _dummy4
			python elichika_db_importer.py
			cd ~/
            ;;
        5)
			clear
      pkill elichika
			cd ~/
			pkg update -y
			pkg upgrade -y
			pkg install python -y
			cd ~/elichika
			rm config_localhost.json
			rm config_catfolk.json
			rm costume_addon_installer.py
			rm live_addon_installer.py
			rm live_addon_uninstall.py
			rm elichika_db_importer.py
			curl -L https://raw.githubusercontent.com/NaufalFajri/as-utility/main/config_localhost_new.json -o config_localhost.json
			curl -L https://raw.githubusercontent.com/arina999999997/elichika/master/config.json -o config_catfolk.json
			curl -L https://raw.githubusercontent.com/NaufalFajri/as-utility/main/costume_addon_installer.py -o costume_addon_installer.py
			curl -L https://raw.githubusercontent.com/NaufalFajri/as-utility/main/live_addon_installer.py -o live_addon_installer.py
			curl -L https://raw.githubusercontent.com/NaufalFajri/as-utility/main/live_addon_installer.py -o live_addon_uninstall.py
			curl -L https://raw.githubusercontent.com/NaufalFajri/as-utility/main/elichika_db_importer.py -o elichika_db_importer.py
			cd assets
			cd db
			rm userdata.db
			curl -L https://codeberg.org/RusdiNgawi/KAMIKAZ-/raw/branch/main/userdata.db -o userdata.db
			cd gl
			rm masterdata.db
			curl -L https://codeberg.org/RusdiNgawi/KAMIKAZ-/raw/branch/main/masterdata.db -o masterdata.db
			cd ~/
			echo "Your account progress has been deleted, DO NOT ENTER TO GAME"
			echo "Select transfer with password"
			echo "Enter this ID & Password"
			echo "ID: 666666666"
			echo "Password: 666666666"
            ;;
        6)
			clear
			pkill elichika
			cd ~/elichika
			cp config_localhost.json config.json
			cd ~/
			echo "Switched to LocalHost"
            ;;
        7)
			clear
			pkill elichika
			cd ~/elichika
			cp config_catfolk.json config.json
			cd ~/
			echo "Switched to Catfolk"
            ;;
        "restore")
			clear
			pkill elichika
			cd ~/elichika
			cd assets
			cd db
			cp backup_new/serverdata.db serverdata.db
			echo "Restored serverdata"
			cp backup_new/userdata.db userdata.db
			echo "Restored userdata"
			cd gl
			cp backup/asset_a_en.db asset_a_en.db
			cp backup/asset_a_ko.db asset_a_ko.db
			cp backup/asset_a_zh.db asset_a_zh.db
			cp backup/asset_i_en.db asset_i_en.db
			cp backup/asset_i_ko.db asset_i_ko.db
			cp backup/asset_i_zh.db asset_i_zh.db
			echo "Restored asset"
			cp backup/dictionary_en_inline_image.db dictionary_en_inline_image.db
			cp backup/dictionary_ko_inline_image.db dictionary_ko_inline_image.db
			cp backup/dictionary_zh_inline_image.db dictionary_zh_inline_image.db
			echo "Restored inline image"
			cp backup/masterdata.db masterdata.db
			echo "Restored masterdata"
			python live_addon_uninstall.py
			cd ~/
			echo "Completed"
            ;;
        "install_elichika")
			clear
			pkill elichika
			echo "You will proceed to browser for downloading app, do not close termux"
			read -p "Press Enter to proceed" _dummy1
			xdg-open https://codeberg.org/RusdiNgawi/KAMIKAZ-/releases/download/0.0.1/signed.apk
			curl -L https://raw.githubusercontent.com/arina999999997/elichika/master/bin/install.sh | bash
            ;;
        "test_codestring")
			clear
			pkill elichika
			echo "Hello World, this just testing"
			read -p "Press Enter to proceed" _dummy2
            ;;
        0)
			clear
            echo "Exiting..."
            exit 0
            ;;
        *)
            echo "Invalid choice. Please enter a valid option."
            ;;
    esac

    read -p "Press Enter to continue..." _dummy
done
