#!/bin/bash

while true; do
    clear
	folder_name="elichika"
    echo "https://github.com/NaufalFajri/as-utility/"
    echo "Elichika Arina Menu:"
	if [ -d "$folder_name" ]; then
    		echo "1. Run Server"
	else
		echo "1. Install Elichika"
	echo "2. Add New Costume (GL)"
	echo "3. Import SQL (GL) (Android) (English)"
	echo "4. Install / Update Dependencies & Script"
	echo "5. Switch to LocalHost"
	echo "6. Switch to Catfolk"
    echo "0. Exit"

    read -p "Enter your choice: " choice

    case $choice in
        1)
			if [ -d "$folder_name" ]; then
				clear
				echo "starting '$folder_name'"
        			pkill elichika
				cd ~/elichika
				./elichika
				cd ~/
			else
				clear
   				echo "installing '$folder_name' (DO NOT CLOSE THIS)."
				curl -L https://raw.githubusercontent.com/arina999999997/elichika/master/bin/install.sh | bash
				echo "Don't Forget Install Dependencies & Script"
            ;;
        2)
			clear
      pkill elichika
			cd ~/elichika
			python costume_addon_installer.py
			cd ~/
            ;;
        3)
			clear
      pkill elichika
			cd ~/elichika
			python elichika_db_importer.py
			cd ~/
            ;;
        4)
			clear
      pkill elichika
			cd ~/
			pkg update
			pkg upgrade
			pkg install python
			cd ~/elichika
			rm config_localhost.json
			rm config_catfolk.json
			rm costume_addon_installer.py
			rm elichika_db_importer.py
			curl -L https://raw.githubusercontent.com/NaufalFajri/as-utility/main/config_localhost_new.json -o config_localhost.json
			curl -L https://raw.githubusercontent.com/arina999999997/elichika/master/config.json -o config_catfolk.json
			curl -L https://raw.githubusercontent.com/NaufalFajri/as-utility/main/costume_addon_installer.py -o costume_addon_installer.py
			curl -L https://raw.githubusercontent.com/NaufalFajri/as-utility/main/elichika_db_importer.py -o elichika_db_importer.py
			cd assets
			cd db
			cd gl
			rm masterdata.db
			curl -L https://codeberg.org/RusdiNgawi/KAMIKAZ-/raw/branch/main/masterdata.db -o masterdata.db
			cd ~/
            ;;
        5)
			clear
			pkill elichika
			cd ~/elichika
			cp config_localhost.json config.json
			echo "Switched to LocalHost"
            ;;
        6)
			clear
			pkill elichika
			cd ~/elichika
			cp config_catfolk.json config.json
			echo "Switched to Catfolk"
            ;;
        0)
			clear
            echo "Exiting..."
            exit 0
            ;;
        *)
            echo "Invalid choice. Please enter a valid option."
            ;;
    esac

    read -p "Press Enter to continue..." _dummy
done
